import { Metadata } from "next";

const keywords = [
  "florist",
  "florist di Bali",
  "Bali florist",
  "Flower delivery Bali",
  "Pengiriman bunga Bali",
  "Wedding flowers Bali",
  "Bunga pernikahan Bali",
  "Online flower shop Bali",
  "Toko bunga online Bali",
  "Best florist in Bali",
  "Florist terbaik di Bali",
  "Flower arrangements Bali",
  "Rangkaian bunga Bali",
  "Birthday flowers Bali",
  "Bunga ulang tahun Bali",
  "Anniversary flowers Bali",
  "Bunga anniversary Bali",
  "Luxury flowers Bali",
  "Bunga mewah Bali",
  "Custom flower bouquets Bali",
  "Buket bunga custom Bali",
  "Event floristry Bali",
  "Florist acara Bali",
  "Corporate flowers Bali",
  "Bunga korporat Bali",
  "Flower decoration Bali",
  "Dekorasi bunga Bali",
  "Floral design Bali",
  "Desain floral Bali",
  "Eco-friendly florist Bali",
  "Florist ramah lingkungan Bali",
];

export const lefloriareMetaData: Metadata = {
  title: "Lefloriare",
  description: "Blooms your day",
  keywords: keywords,
};
